### ISSUE TITLE
Game display bug and illegal state exception

### ISSUE THREAD

**Issue by tgsachse** [tgsachse/escala#72]
Exception in thread "main" java.lang.IllegalStateException: Component must have a valid peer
	at java.desktop/java.awt.Component$FlipBufferStrategy.getBackBuffer(Component.java:4125)
	at java.desktop/java.awt.Component$FlipBufferStrategy.updateInternalBuffers(Component.java:4108)
	at java.desktop/java.awt.Component$FlipBufferStrategy.revalidate(Component.java:4223)
	at java.desktop/java.awt.Component$FlipBufferStrategy.revalidate(Component.java:4205)
	at java.desktop/java.awt.Component$FlipBufferStrategy.getDrawGraphics(Component.java:4197)
	at escala.Viewer.run(Viewer.java:174)
	at escala.Escala.<init>(Escala.java:28)
	at escala.Escala.main(Escala.java:33)

**Comment by tgsachse** [comment]
Handled in sprint 2
